c++ code for finding longest palindromic substring in a string
godkingjay/LeetCode pull request #184
Opened 2023-10-27 06:47 UTC by chiku011

solved problem #182 
 i added a solution for finding longest palindromic substring in a given subtring in c++ language

2023-10-27 17:37 UTC, chiku011 commented
can you plz merge it or if you want to some changes then plz tell me

2023-10-28 00:30 UTC, godkingjay requested changes
Thank you for your contribution. Please provide the solution tested in [LeetCode](https://leetcode.com/problems/longest-palindromic-substring/). Thank you.

2023-10-28 07:08 UTC, chiku011 commented
hii i changed the code with leetcode tested solution plz check it and merge it

2023-10-29 00:43 UTC, godkingjay approved these changes

2023-10-29 00:44 UTC, merged