Raunak
godkingjay/LeetCode pull request #59
Opened 2023-10-07 20:38 UTC by oyerounak

Added more solutions and new approach to some Median and Hard level Questions

2023-10-08 00:24 UTC, godkingjay requested changes
Thank you for your contributions. However there seems to be a problem for your solution in:

### [4. Median of Two Sorted Arrays](https://leetcode.com/problems/median-of-two-sorted-arrays/)

- Java Solution
![image](https://github.com/godkingjay/LeetCode/assets/89616705/ca859b96-22fa-44fc-9541-fde80a89d524)

2023-10-08 06:37 UTC, oyerounak commented
**_For sure I will make the changes with a more understanding code for beginners._**

2023-10-08 07:22 UTC, godkingjay commented on Hard/4. Median of Two Sorted Arrays/New approach[Arraylist]/Solution.java
Don't forget to fix this solution. Thank you.

2023-10-08 07:29 UTC, oyerounak reviewed
Here is the solution to Hard/4.Median of Two Sorted Arrays/New approach[add two array]

2023-10-08 08:18 UTC, godkingjay commented
> Here is the solution to Hard/4.Median of Two Sorted Arrays/New approach[add two array]

I know. However, it fails some of the test cases once submitted, it passes `2057` out of the `2094` testcases:

![image](https://github.com/godkingjay/LeetCode/assets/89616705/4da22185-c7f8-4df5-bea0-ca2ed8bd5ef2)

2023-10-08 08:22 UTC, oyerounak commented
`int a = nums1.length;
        int b = nums2.length;
    
        // Calculate the total length of the merged array
        int c = a + b;
    
        // Create a new integer array to hold the merged elements
        int[] arr = new int[c];
    
        // Copy elements from nums1 into arr
        for (int i = 0; i < a; i++) {
            arr[i] = nums1[i];
        }
    
        // Copy elements from nums2 into arr, starting from position a
        for (int i = 0; i < b; i++) {
            arr[a + i] = nums2[i];
        }
    
        // Sort the merged array in ascending order
        Arrays.sort(arr);
    
        // Check if the length of the merged array is even or odd
        if (c % 2 == 0) {
            // Calculate the indices of the two middle elements
            int mid1 = (c - 1) / 2;
            int mid2 = mid1 + 1;
    
            // Calculate the median as the average of the two middle elements
            return (double) (arr[mid1] + arr[mid2]) / 2;
        } else {
            // Calculate the index of the middle element
            int mid = (c - 1) / 2;
    
            // Return the middle element as the median
            return arr[mid];
        }`
        Here is the code for it

2023-10-08 08:28 UTC, godkingjay commented
> ```java
>		int a = nums1.length;
> 	int b = nums2.length;
> 
>     // Calculate the total length of the merged array
>     int c = a + b;
> 
>     // Create a new integer array to hold the merged elements
>     int[] arr = new int[c];
> 
>     // Copy elements from nums1 into arr
>     for (int i = 0; i < a; i++) {
>         arr[i] = nums1[i];
>     }
> 
>     // Copy elements from nums2 into arr, starting from position a
>     for (int i = 0; i < b; i++) {
>         arr[a + i] = nums2[i];
>     }
> 
>     // Sort the merged array in ascending order
>     Arrays.sort(arr);
> 
>     // Check if the length of the merged array is even or odd
>     if (c % 2 == 0) {
>         // Calculate the indices of the two middle elements
>         int mid1 = (c - 1) / 2;
>         int mid2 = mid1 + 1;
> 
>         // Calculate the median as the average of the two middle elements
>         return (double) (arr[mid1] + arr[mid2]) / 2;
>     } else {
>         // Calculate the index of the middle element
>         int mid = (c - 1) / 2;
> 
>         // Return the middle element as the median
>         return arr[mid];
>     }
> ```

This solution of yours works, however, you still haven't pushed this solution yet.

2023-10-16 00:40 UTC, godkingjay approved these changes
Thank you for your contributions!

2023-10-16 00:41 UTC, merged